# nixpacks.toml

[phases.setup]
# Use Java 21, which is a stable LTS version.
jdk_version = "21"

[phases.build]
# Add 'clean' to ensure no old artifacts interfere.
# Add a Gradle property to explicitly turn off the daemon.
cmds = ["./gradlew clean build -x test --no-daemon -Dorg.gradle.daemon=false"]

[start]
# The start command remains the same.
cmd = "java -Dserver.port=${PORT} -jar build/libs/*.jar"
