# nixpacks.toml

[phases.setup]
# Use the Nix package for Eclipse Temurin JDK 21
nixPkgs = ["...", "pkgs.temurin-21-jdk"]

[phases.build]
cmds = ["./gradlew build --no-daemon -x test"]

[start]
cmd = "java -Dserver.port=${PORT} -jar build/libs/*.jar"
