# nixpacks.toml

# Tell Nixpacks which providers (languages) to use.
# It will automatically detect it needs Gradle from your build.gradle file.
providers = ["java"]

# Configure the Java provider by setting the version.
# Nixpacks will find the appropriate package for this version itself.
[phases.setup]
jdk_version = "21"

# We can remove the explicit build and start commands for now,
# as Nixpacks is smart enough to detect Gradle and the Procfile.
# Let's rely on its conventions first.
